#!/usr/bin/env ruby

git_bundles = [ 
	"git://github.com/scrooloose/nerdtree.git",
	"git://github.com/scrooloose/nerdcommenter.git",
	"git://github.com/tpope/vim-fugitive.git",
	"git://github.com/tpope/vim-git.git",
	"git://github.com/tpope/vim-markdown.git",
	"git://github.com/chrismetcalf/vim-yankring.git",
	"git://github.com/mattn/gist-vim.git",
	"git://github.com/mhz/vim-matchit.git",

	#"git://github.com/motemen/git-vim.git", # not as good as fugitive - depends on PWD
	#"git://github.com/tpope/vim-cucumber.git",
	#"git://github.com/tpope/vim-haml.git",
	#"git://github.com/tpope/vim-rails.git",
	#"git://github.com/tpope/vim-repeat.git",
	#"git://github.com/tpope/vim-surround.git",
	#"git://github.com/tpope/vim-vividchalk.git",
	#"git://github.com/tsaleh/vim-align.git",
	#"git://github.com/tsaleh/vim-shoulda.git",
	#"git://github.com/tsaleh/vim-supertab.git",
	#"git://github.com/tsaleh/vim-tcomment.git",
	#"git://github.com/vim-ruby/vim-ruby.git",
]

vim_org_scripts = [
	["IndexedSearch", "7062", "plugin"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

notrash = ARGV.include?('--notrash')

unless notrash
	puts "Trashing everything (lookout!)"
	Dir["*"].each {|d| FileUtils.rm_rf d }
end

git_bundles.each do |url|
	dir = url.split('/').last.sub(/\.git$/, '')
	if notrash && File.exists?(dir)
		puts "  Skipping #{dir}"
		next
	end
	puts "  Unpacking #{url} into #{dir}"
	`git clone #{url} #{dir}`
	FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
	local_file = File.join(name, script_type, "#{name}.#{script_type == 'zip' ? 'zip' : 'vim'}")
	if notrash && File.exists?(local_file)
		puts "  Skipping #{local_file}"
		next
	end
	puts " Downloading #{name}"
	FileUtils.mkdir_p(File.dirname(local_file))
	File.open(local_file, "w") do |file|
		file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
	end
	if script_type == 'zip'
		%x(unzip -d #{name} #{local_file})
	end
end

`vim -e -c"call pathogen#runtime_append_all_bundles()" -c "call pathogen#helptags()" -c q`
